// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VibroMonitor.Data;

#nullable disable

namespace VibroMonitor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260602033321_Images")]
    partial class Images
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VibroMonitor.Models.AlarmItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Acked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("AckedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EquipmentItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("EquipmentPointId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sensor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentItemId");

                    b.HasIndex("EquipmentPointId");

                    b.ToTable("AlarmItem");
                });

            modelBuilder.Entity("VibroMonitor.Models.EquipmentImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("EquipmentItemId")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsThumbnail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentItemId");

                    b.ToTable("EquipmentImages");
                });

            modelBuilder.Entity("VibroMonitor.Models.EquipmentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EquipmentItems");
                });

            modelBuilder.Entity("VibroMonitor.Models.EquipmentPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipmentItemId")
                        .HasColumnType("integer");

                    b.Property<double>("Hi")
                        .HasColumnType("double precision");

                    b.Property<double>("HiHi")
                        .HasColumnType("double precision");

                    b.Property<double>("Lo")
                        .HasColumnType("double precision");

                    b.Property<double>("LoLo")
                        .HasColumnType("double precision");

                    b.Property<string>("MqttTopic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentItemId");

                    b.ToTable("EquipmentPoints");
                });

            modelBuilder.Entity("VibroMonitor.Models.PointHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipmentPointId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("PointHistory");
                });

            modelBuilder.Entity("VibroMonitor.Models.AlarmItem", b =>
                {
                    b.HasOne("VibroMonitor.Models.EquipmentItem", null)
                        .WithMany("Alarms")
                        .HasForeignKey("EquipmentItemId");

                    b.HasOne("VibroMonitor.Models.EquipmentPoint", "EquipmentPoint")
                        .WithMany()
                        .HasForeignKey("EquipmentPointId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EquipmentPoint");
                });

            modelBuilder.Entity("VibroMonitor.Models.EquipmentImage", b =>
                {
                    b.HasOne("VibroMonitor.Models.EquipmentItem", "EquipmentItem")
                        .WithMany("Images")
                        .HasForeignKey("EquipmentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentItem");
                });

            modelBuilder.Entity("VibroMonitor.Models.EquipmentPoint", b =>
                {
                    b.HasOne("VibroMonitor.Models.EquipmentItem", "EquipmentItem")
                        .WithMany("Points")
                        .HasForeignKey("EquipmentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentItem");
                });

            modelBuilder.Entity("VibroMonitor.Models.EquipmentItem", b =>
                {
                    b.Navigation("Alarms");

                    b.Navigation("Images");

                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
