// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VibroMonitor.Data;

#nullable disable

namespace VibroMonitor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601023238_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VibroMonitor.Models.AlarmItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acknowledged")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Created")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EquipmentItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sensor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentItemId");

                    b.ToTable("AlarmItem");
                });

            modelBuilder.Entity("VibroMonitor.Models.EquipmentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EquipmentItems");
                });

            modelBuilder.Entity("VibroMonitor.Models.EquipmentPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipmentItemId")
                        .HasColumnType("integer");

                    b.Property<double>("Hi")
                        .HasColumnType("double precision");

                    b.Property<double>("HiHi")
                        .HasColumnType("double precision");

                    b.Property<double>("Lo")
                        .HasColumnType("double precision");

                    b.Property<double>("LoLo")
                        .HasColumnType("double precision");

                    b.Property<string>("MqttTopic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentItemId");

                    b.ToTable("EquipmentPoints");
                });

            modelBuilder.Entity("VibroMonitor.Models.AlarmItem", b =>
                {
                    b.HasOne("VibroMonitor.Models.EquipmentItem", null)
                        .WithMany("Alarms")
                        .HasForeignKey("EquipmentItemId");
                });

            modelBuilder.Entity("VibroMonitor.Models.EquipmentPoint", b =>
                {
                    b.HasOne("VibroMonitor.Models.EquipmentItem", "EquipmentItem")
                        .WithMany("Points")
                        .HasForeignKey("EquipmentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentItem");
                });

            modelBuilder.Entity("VibroMonitor.Models.EquipmentItem", b =>
                {
                    b.Navigation("Alarms");

                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
